### ISSUE TITLE
Router issue for new page 

### ISSUE THREAD

**Issue by ci30** [imSanjaySoni/Inshorts-Clone-The-News-App#16]
Why you are comment all Router usage line?
For example if we want to open the setting page right now it not work bcz you comment the relative code in the source.

**Comment by ci30** [comment]
Base of change log some body change it to update dependency but i think he forget to add this line `Rouut.navigator.pushNamed(Rouut.settingsScreen); `
 in some case .

**Comment by rgbufferchime** [comment]
may i know which flutter sdk version are you all using to compile
