### ISSUE TITLE
It is possible to add news from admin panel.

### ISSUE THREAD

**Issue by kishorindia420** [imSanjaySoni/Inshorts-Clone-The-News-App#4]

**Comment by imSanjaySoni** [comment]
Yes it is possible but you need to work on admin pannel feature where you can post news. And and also need to add new category for get request.

**Comment by imSanjaySoni** [comment]
> _No description provided._

Currently it fetching data from newsapi.org only

**Comment by kishorindia420** [comment]
It is possible to you to add admin panel features.

**Comment by imSanjaySoni** [comment]
Every thing is possible if you can

**Comment by imSanjaySoni** [comment]
@kishorindia420  Hope you will work on this ✌️ best regards
